<?php
use SilverStripe\ORM\DataObject;

class SkippitSigndb extends DataObject{
    private static $db = array(
        'email' => 'Varchar(100)',
        'name' => 'Varchar(100)',
        'username' => 'Varchar(100)',
        'password' => 'Varchar(100)',
        'friendemail' => 'Varchar(100)',
        'referrals' => 'Varchar(100)',
        'peoplebehine' => 'Varchar(100)',
        'peopleafter' => 'Varchar(100)',
        'paint' => 'Varchar(100)',
        'music' => 'Varchar(100)',
        'book' => 'Varchar(100)',
        'game' => 'Varchar(100)',
        'sport' => 'Varchar(100)',
        'movie' => 'Varchar(100)',
        'introduction' => 'Varchar(100)',
        'schedulefree' => 'Varchar(100)',
        'scheduledate' => 'Varchar(100)',
        'chat' => 'Varchar(100)',
        'match' => 'Varchar(100)',
        'unmatch' => 'Varchar(100)',
        'datedrink' => 'Varchar(100)',
        'datemovie' => 'Varchar(100)',
        'datedinner' => 'Varchar(100)',
        'dateeventtime' => 'Varchar(100)',
        'offers' => 'Varchar(100)',
        'active' => 'Varchar(100)',
        'address' => 'Varchar(100)',
        'hobbies' => 'Varchar(100)',
        'photo1' => 'Varchar(100)',
        'photo2' => 'Varchar(100)',
        'photo3' => 'Varchar(100)',
        'video' => 'Varchar(100)'
    );
    private static $summary_fields = array(
        'email' => 'Email',
        'name' => 'Name',
        'username' => 'Username',
        'password' => 'Password',
        'friendemail' => 'Friend-email',
        'referrals' => 'Referral',
        'peoplebehine' => 'People-behind',
        'peopleafter' => 'People-after',
        'paint' => 'Paint',
        'music' => 'Music',
        'book' => 'Book',
        'game' => 'Game',
        'sport' => 'Sport',
        'movie' => 'Movie',
        'introduction' => 'Introduction',
        'schedulefree' => 'Schedule-free',
        'scheduledate' => 'Schedule-date',
        'chat' => 'Chat',
        'match' => 'Match',
        'unmatch' => 'Unmatch',
        'datedrink' => 'Date-drink',
        'datemovie' => 'Date-movie',
        'datedinner' => 'Date-dinner',
        'dateeventtime' => 'Date-event-time',
        'offers' => 'Offers',
        'active' => 'Active',
        'address' => 'Address',
        'hobbies' => 'Hobbies',
        'photo1'=> 'Photo-1',
        'photo2'=> 'Photo-2',
        'photo3'=> 'Photo-3',
        'video'=> 'Video'
    );
}
